#!/bin/bash
#$ -wd /data/EECS-YuanLab/ruthwik/code_to_run/TSG
#$ -j y
#$ -pe smp 12 
#$ -l h_rt=1:00:00
#$ -l h_vmem=7.5G
#$ -l gpu=1
#$ -o logs/
#$ -l gpu_type=ampere
#$ -l cluster=andrena


# Load modules
module purge

module load python/3.10.7
module load cuda/11.8.0
module load gcc/6.3.0
module load java/1.8.0_382-openjdk

# ml python/3.10.7 cuda/11.8.0 gcc/6.3.0 java/1.8.0_382-openjdk

module list

# Activate virtual environment
source .venv/bin/activate



python eval_tsg.py --dump_images 0 \
    --num_images 5000 \
    --model /data/scratch/ec23759/tsgmt1/modeltsgmt1_do40018.pth \
    --infos_path /data/scratch/ec23759/tsgmt1/infos_tsgmt1_do40018.pkl  \
    --language_eval 1 \
    --beam_size 5 \
    --input_label_h5 /data/EECS-YuanLab/COCO/cocotalk_label.h5