#!/bin/bash
#$ -l h_rt=24:00:00
#$ -l h_vmem=7.5G
#$ -pe smp 12
#$ -l gpu=1
#$ -l gpu_type=ampere
#$ -wd /data/home/eey362/code/TSG
#$ -j y
#$ -m ea
#$ -o logs/
#$ -l cluster=andrena


# Load modules
module purge

module load python/3.10.7
module load cuda/11.8.0
module load gcc/6.3.0
module load java/1.8.0_382-openjdk

# Activate virtual environment
source .venv/bin/activate

# Run!
python3 train_tsg.py --cfg ./tsg_configs/andrena.yml
